# Site settings
title: Göncz
email: robert@goncz.org
author: Robert Göncz
description:
url: https://goncz.org

# Build settings
permalink: :title/
sass:
  sass_dir: css

exclude:
  - README.md
  - CNAME